In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.api.types import is_numeric_dtype
import warnings
warnings.filterwarnings('ignore')
import h5py

In [22]:
trainfile = 'train_catvnoncat.h5'
testfile = 'test_catvnoncat.h5'

train_dataset = h5py.File(trainfile, "r")
test_dataset = h5py.File(testfile, "r")


x_train_data = np.reshape(np.array(train_dataset['train_set_x'][:]), (np.array(train_dataset['train_set_x'][:]).shape[0], -1))
y_train_data = (np.array([train_dataset['train_set_y'][:]]))

x_test_data = np.reshape(np.array(test_dataset['test_set_x'][:]), (np.array(test_dataset['test_set_x'][:]).shape[0], -1))
y_test_data = (np.array([test_dataset['test_set_y'][:]]))

y_test_data = y_test_data .T
y_train_data = y_train_data.T

print("x_train_data : ",x_train_data.shape)
print("y_train_data : ",y_train_data.shape)
print("x_test_data : ",x_test_data.shape)
print("y_test_data : ",y_test_data.shape)

x_train_data :  (209, 12288)
y_train_data :  (209, 1)
x_test_data :  (50, 12288)
y_test_data :  (50, 1)


In [23]:
print(x_train_data.shape)
print(y_train_data.shape)
print(x_test_data.shape)
print(y_test_data.shape)

(209, 12288)
(209, 1)
(50, 12288)
(50, 1)


In [24]:
w = np.random.rand(x_train_data.shape[1], 1) * 0.01 # Weights matrix = ()
b = np.ones((1, 1), dtype='float') # Bais matrix = (1 x 1)
print(w.shape)
print(b.shape)
b

(12288, 1)
(1, 1)


array([[1.]])

In [25]:
z = np.dot(w.T, x_train_data.T) + b
z.shape

(1, 209)

In [26]:
a = 1 / 1 + np.exp(-z)
a.shape

(1, 209)

In [27]:
dz = a - y_train_data.T
dz.shape

(1, 209)

In [28]:
dw = np.dot(dz, x_train_data) / x_train_data.shape[0]
dw.shape

(1, 12288)

In [30]:
db = np.sum(dz) / x_train_data.shape[0]
db = db.reshape(1,1)
print(db.shape)
db

(1, 1)


array([[0.65550239]])

In [31]:
l_rate = 0.001
w = w - l_rate * dw.T

dw.shape, w.shape

((1, 12288), (12288, 1))

In [32]:
b = b - l_rate * db.T
b

array([[0.9993445]])

In [33]:
epochs = 1
l_rate = 0.01
for i in range(epochs):
    z = np.dot(w.T, x_train_data.T) + b
    a = 1 / 1 + np.exp(-z)

    dz = a - y_train_data.T
    dw = np.dot(dz, x_train_data) / x_train_data.shape[0]
    db = np.sum(dz) / x_train_data.shape[0]
    db = db.reshape(1,1)

    w = w - l_rate * dw.T
    b = b - l_rate * db
    
print(w.shape,b)
    

(12288, 1) [[-inf]]


In [34]:
z = np.dot(w.T, x_test_data.T) + b # Z = W*X = (1 x m)
pred =  1 / 1 + np.exp(-z) #  Activation function = sigmoid(-z) = (1 x m)
pred.shape

(1, 50)

In [35]:
pred.shape

(1, 50)

In [36]:
# train_accuracy = (100 - np.mean(np.abs(pred_train - y_train_data)) * 100)
test_accuracy = 100 - (np.mean((pred - y_test_data)) * 100)

# print("train_accuracy = ", train_accuracy)
print("test_accuracy = ", test_accuracy)


test_accuracy =  nan
