In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.api.types import is_numeric_dtype
import warnings
warnings.filterwarnings('ignore')

In [98]:
df =pd.read_csv("bank.csv", delimiter=";")
df.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [99]:
df.y.replace(('yes', 'no'), (1, 0), inplace=True)

In [100]:
categorical_data = []
for name in list(df.columns):
    if is_numeric_dtype(df[name]):
        pass
    else:
        categorical_data.append(name)

df = pd.get_dummies(df, columns=categorical_data)

df.shape

(4521, 52)

In [101]:
y_data_set = pd.DataFrame(df.y)
x_data_set = df.drop(["y"], axis=1)

train_size = int(np.ceil((len(y_data_set) * 80) / 100))
test_size = int(len(y_data_set) - train_size)

x_train_data = np.array(x_data_set[:train_size])
y_train_data = np.array(y_data_set[:train_size])
x_test_data = np.array(x_data_set[train_size:])
y_test_data = np.array(y_data_set[train_size:])    

In [102]:
print(x_train_data.shape)
print(y_train_data.shape)
print(x_test_data.shape)
print(y_test_data.shape)

(3617, 51)
(3617, 1)
(904, 51)
(904, 1)


In [103]:
w = np.random.rand(x_train_data.shape[1], 1) * 0.01 # Weights matrix = ()
b = np.ones((1, 1), dtype='float') # Bais matrix = (1 x 1)
print(w.shape)
print(b.shape)
b

(51, 1)
(1, 1)


array([[1.]])

In [79]:
z = np.dot(w.T, x_train_data.T) + b
z.shape

(1, 3617)

In [80]:
a = 1 / 1 + np.exp(-z)
a.shape

(1, 3617)

In [81]:
dz = a - y_train_data.T
dz.shape

(1, 3617)

In [57]:
dw = np.dot(dz, x_train_data) / x_train_data.shape[0]
dw.shape

(1, 51)

In [82]:
db = np.sum(dz) / x_train_data.shape[0]
db = db.reshape(1,1)
print(db.shape)
db

(1, 1)


array([[276.11331617]])

In [83]:
l_rate = 0.001
w = w - l_rate * dw.T

dw.shape, w.shape

((1, 51), (51, 1))

In [84]:
b = b - l_rate * db.T
b

array([[0.72388668]])

In [104]:
epochs = 1
l_rate = 0.01
for i in range(epochs):
    z = np.dot(w.T, x_train_data.T) + b
    a = 1 / 1 + np.exp(-z)

    dz = a - y_train_data.T
    dw = np.dot(dz, x_train_data) / x_train_data.shape[0]
    db = np.sum(dz) / x_train_data.shape[0]
    db = db.reshape(1,1)

    w = w - l_rate * dw.T
    b = b - l_rate * db
    
print(w.shape,b)
    

(51, 1) [[0.98959506]]


In [105]:
z = np.dot(w.T, x_test_data.T) + b # Z = W*X = (1 x m)
pred =  1 / 1 + np.exp(-z) #  Activation function = sigmoid(-z) = (1 x m)
pred.shape

(1, 904)

In [111]:
pred.shape

(1, 904)

In [114]:
# train_accuracy = (100 - np.mean(np.abs(pred_train - y_train_data)) * 100)
test_accuracy = 100 - (np.mean((pred - y_test_data)) * 100)

# print("train_accuracy = ", train_accuracy)
print("test_accuracy = ", test_accuracy)
